### ISSUE TITLE
Building executable with pyinstaller fails

### ISSUE THREAD

**Issue by Heregon** [richardhuskey/asteroid_impact#4]
Pyinstaller fails to execute because the game-win.spec is missing

```
C:\Users\myusername\Desktop\asteroid_impact_source_code>pyinstaller.exe game-win.spec --noconfirm
108 INFO: PyInstaller: 3.2.1
108 INFO: Python: 2.7.11
109 INFO: Platform: Windows-10-10.0.15019
112 INFO: UPX is not available.
Traceback (most recent call last):
  File "C:\Program Files\Python27\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "c:\program files\python27\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\program files\python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\program files\python27\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\program files\python27\lib\site-packages\PyInstaller\building\build_main.py", line 732, in build
    with open(spec, 'r') as f:
IOError: [Errno 2] No such file or directory: 'game-win.spec'
```

**Comment by richardhuskey** [comment]
Hello,

The updated code now includes the game-win.spec file as well as extra documentation on how to do a standalone build using Pyinstaller. Should solve the issue.
